[package]
name = "gen_reqwest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_core = { path = "../gen_core" }

serde = { workspace = true }
anyhow = { workspace = true }
reqwest = "0.11.16"
